repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        types: [python]
        entry: poetry run ruff check --fix .

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        types: [python]
        entry: poetry run mypy .
        pass_filenames: false
