"""create_blog_posts_table

Revision ID: 6a04e2988aa9
Revises: b9dd868838e2
Create Date: 2024-05-28 09:49:43.569138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a04e2988aa9"
down_revision: Union[str, None] = "b9dd868838e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=False),
            default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=False),
            default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            onupdate=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_user_email", "users", ["email"])
    op.create_unique_constraint("uq_user_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_username", "users", type_="unique")
    op.drop_constraint("uq_user_email", "users", type_="unique")
    op.drop_table("blog_posts")
    # ### end Alembic commands ###
