TOKEN_URL = "/api/v1/auth/login"

# APP Settings
SERVER_HOST_DEFAULT = "localhost"
SERVER_PORT_DEFAULT = 8000
LOG_LEVEL_DEFAULT = "DEBUG"
ENABLE_ACCESS_LOG_DEFAULT = True
ENABLE_RELOAD_DEFAULT = False

# PG Settings
PG_ENV_PREFIX = "PG_"
PG_USERNAME_DEFAULT = "postgres"
PG_PASSWORD_DEFAULT = "postgres"
PG_HOST_DEFAULT = "localhost"
PG_PORT_DEFAULT = 5432
PG_DATABASE_DEFAULT = "postgres"

# Secret Settings
SECRET_ENV_PREFIX = "SECRET_"
SECRET_ALGORITHM_DEFAULT = "HS256"
SECRET_ACCESS_TOKEN_EXPIRE_MINUTES_DEFAULT = 30
